services:
  ground-station:
    build: ground-station
    privileged: true
    ports:
      - "33845:33845"
    restart: on-failure
  tile_server:
    build: tile-server
    volumes:
      - ./tile-server/mapping_tiles:/usr/src/app/mapping_tiles:ro
    ports:
      - "8000:80"
    restart: on-failure
  ground-station-ui:
    build: ground-station-ui
    ports:
      - "4173:4173"
    depends_on:
      - ground-station
      - tile_server
    restart: unless-stopped